site_name: "SSO & Spring  : créez une authentification centralisée de A à Z"
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
nav:
  - Accueil: index.md
  - Séquence 0 :
      - Introduction: sequences/s0/index.md
  - Séquence 1:
      - Test de positionnement: sequences/s1/positionnement/index.md
      - Fondamentaux:
          - Accueil: sequences/s1/fondamentaux/index.md
          - Introduction: sequences/s1/fondamentaux/introduction.md
          - POO: sequences/s1/fondamentaux/poo.md
  - Séquence 2 :
      - Docker: sequences/s2/docker/index.md
      - Installation de docker: sequences/s2/docker/installation.md
      - Initialisation du projet:
          - Création du projet Spring Boot avec Spring Initializr: sequences/s2/init_projet/creation_projet.md
          - Dockerisation de l’application: sequences/s2/init_projet/dockerisation.md
  - Séquence 3 :
      - Structuration du projet:
          - Rappel et principes de l’architecture MVC: sequences/s3/mvc/rappels.md
          - Création de l’architecture: sequences/s3/mvc/creation_archi.md
          - Bonnes pratiques: sequences/s3/mvc/bonnes_pratiques.md

